version: '3'
services:
  api-gateway:
    build: ./services/apiGateway
    ports:
      - "5000:8080"

  order:
    build: ./services/order
    ports:
      - "6001:8080"
    depends_on:
      - "mongo"
    restart: "on-failure"

  mongo:
    image: mongo:4.0.4
    environment:
      - MONGO_INITDB_DATABASE=distributed-messaging
    ports:
      - "27017:27017"
      - "28001:27017"
    volumes:
      - './temp/volume/data:/data/db'