version: 2
jobs:
  test:
    docker:
      - image: ypereirareis/docker-compose
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: docker-compose -f ./docker-composition/docker-compose-ci-tests.yml up

workflows:
  version: 2
  build-and-test:
    jobs:
      - test