version: 2
jobs:
  test:
    docker:
      - image: ypereirareis/docker-compose
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run services
          command: COMPOSE_PROJECT_NAME=distributedmessaging docker-compose -f ./docker-composition/docker-compose-ci-dependencies.yml down && COMPOSE_PROJECT_NAME=distributedmessaging docker-compose -f ./docker-composition/docker-compose-ci-dependencies.yml up
          background: true
      - run:
          name: Run tests
          command: COMPOSE_PROJECT_NAME=distributedmessaging docker-compose -f ./docker-composition/docker-compose-ci-tests.yml up
          environment:
            JEST_JUNIT_OUTPUT: ~/repo/e2e/test-results/junit/results.xml
      - store_artifacts:
          path: ./e2e/test-results/junit
      - store_test_results:
          path: ./e2e/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - test