version: 2
jobs:
  test:
    docker:
      - image: ypereirareis/docker-compose
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run services
          command: docker-compose -f ./docker-composition/docker-compose-kafka.yml -f ./docker-composition/docker-compose-persistence.yml -f ./docker-composition/docker-compose-services.yml up
          background: true
      - run:
          name: Run tests
          command: docker-compose -f ./docker-composition/docker-compose-ci-tests.yml up
      - store_test_results:
          path: ~/repo/e2e/reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - test