version: 2
jobs:
  runs-services:
    docker:
      - image: ypereirareis/docker-compose
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: start services
          command: docker-compose -f ./docker-composition/docker-compose-services.yml up

  e2e-tests:
    working_directory: ~/repo/e2e
      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        - run: npm install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        # run tests!
        - run: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - runs-services
      - e2e-tests:
          requires:
            - runs-services