version: 2
jobs:
  start-services:
    docker:
      - image: ypereirareis/docker-compose
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start services
          command: docker-compose -f ./docker-composition/docker-compose-services.yml up -d

  e2e-tests:
    docker:
      - image: circleci/node:8.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show directory
          command: |
            pwd
            ls
      - run:
          name: Install dependencies
          command: cd e2e && npm install
      - run:
          name: Run tests
          command: cd e2e && npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - start-services
      - e2e-tests:
          requires:
            - start-services