version: 2
jobs:
  test:
    docker:
      - image: ypereirareis/docker-compose
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run services
          command: COMPOSE_PROJECT_NAME=distributedmessaging docker-compose -f ./docker-composition/docker-compose-ci-dependencies.yml down && COMPOSE_PROJECT_NAME=distributedmessaging docker-compose -f ./docker-composition/docker-compose-ci-dependencies.yml up
          background: true
      - run:
          name: Run tests
          command: COMPOSE_PROJECT_NAME=distributedmessaging docker-compose -f ./docker-composition/docker-compose-ci-tests.yml up
      - store_artifacts:
          path: ~/repo/e2e/junit
      - store_test_results:
          path: ~/repo/e2e/

workflows:
  version: 2
  build-and-test:
    jobs:
      - test