FROM node:10.14.0-alpine

RUN apk --no-cache add \
      bash \
      curl

COPY apiGateway /services/apiGateway
COPY shared /services/shared

WORKDIR /services/apiGateway

RUN npm install

EXPOSE 8090

CMD ["node", "index.js"]