version: '2'
services:

# tests
  e2e-tests:
    image: e2e-tests:latest
    build:
      context: ../e2e
      dockerfile: Dockerfile-e2e
    volumes:
      - ~/repo/test-results:/test-results
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    command: |
      ls .
      ls ./test-results
      npm run test:CI
      ls .
    environment:
      - JEST_JUNIT_OUTPUT=./test-results/junit/results.xml