version: '2'
services:

# tests
  e2e-tests:
    image: e2e-tests:latest
    build:
      context: ../e2e
      dockerfile: Dockerfile-e2e
    volumes:
      - ../e2e/test-results:/test-results
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    command: npm run test:CI
    environment:
      - JEST_JUNIT_OUTPUT: ~/repo/e2e/test-results/junit/results.xml