version: '2'
services:

  # kafka
  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    restart: always
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  # persistence
  mongo:
    image: mongo:3.4.19-jessie
    restart: always
    ports:
      - "27017:27017"

  # services
  api-gateway:
    image: api-gateway:latest
    restart: always
    build:
      context: ../services
      dockerfile: Dockerfile-apiGateway
    ports:
      - "8900:8090"
    environment:
      APP_HOSTNAME: "0.0.0.0"
      APP_PORT: 8090
      SERVICE_ADDRESS_ORDER: "http://order:8092"

  inventory:
    image: inventory:latest
    restart: always
    build:
      context: ../services
      dockerfile: Dockerfile-inventory
    ports:
      - "8901:8091"
    environment:
      APP_HOSTNAME: "0.0.0.0"
      APP_PORT: 8091
      DB_MONGO_CONNECTION_STRING: "mongodb://mongo:27017/distributed-messaging"
      KAFKA_METADATA_BROKER_LIST: "kafka:9092"
      SERVICE_ADDRESS_ORDER: "http://order:8092"

  order:
    image: order:latest
    restart: always
    build:
      context: ../services
      dockerfile: Dockerfile-order
    ports:
      - "8902:8092"
    environment:
      APP_HOSTNAME: "0.0.0.0"
      APP_PORT: 8092
      DB_MONGO_CONNECTION_STRING: "mongodb://mongo:27017/distributed-messaging"
      KAFKA_METADATA_BROKER_LIST: "kafka:9092"

  notification:
    image: notification:latest
    restart: always
    build:
      context: ../services
      dockerfile: Dockerfile-notification
    ports:
      - "8903:8093"
      - "8904:8094"
    environment:
      APP_HOSTNAME: "0.0.0.0"
      APP_PORT: 8093
      APP_PORT_WEBSOCKET: 8094
      KAFKA_METADATA_BROKER_LIST: "kafka:9092"