version: '2'
services:

# tests
  e2e-tests:
    image: e2e-tests:latest
    build:
      context: ../e2e
      dockerfile: Dockerfile-e2e
    volumes:
      - ../e2e/test-results:/test-results
      - ~/repo/e2e/test-results:/test-results
      - ~/root/repo/e2e/test-results:/test-results
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    command:
      - /bin/bash
      - -c
      - |
        echo 'pwd' $$(pwd)
        echo 'ls .' $$(ls .)
        npm run test:CI
    environment:
      - JEST_JUNIT_OUTPUT=./test-results/junit/results.xml