version: '3'
services:
  mongo:
    image: mongo:4.0.4
    environment:
      - MONGO_INITDB_DATABASE=distributed-messaging
    ports:
      - "27017:27017"
      - "28001:27017"
    volumes:
      - '/data/db:/data/db'
