const RESOURCE_MAP = {
  ORDER: 'ORDER',
  INVENTORY: 'INVENTORY'
}

const OPERATION_MAP = {
  CREATE: 'CREATE',
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED'
}

const MESSAGE_TYPE_MAP = {
  COMMAND: 'COMMAND',
  QUERY: 'QUERY',
  EVENT: 'EVENT'
}

module.exports = {
  RESOURCE_MAP,
  OPERATION_MAP,
  MESSAGE_TYPE_MAP
}
